---
title: "sql_hw"
author: "octopus"
date: '2 мая 2017 г '
output: html_document
---

## libs

```{r libs, warning=F, message=F}
library(RSQLite)
library(DBI)
```

## read db

```{r setup, warning=FALSE, message=F, cache=TRUE}
mydb <- dbConnect(RSQLite::SQLite(), "data.sqlite")
dbListTables(mydb)
```

## queries

```{r echo=TRUE}
# 1. Перечислить пользователей в алфавитном порядке username (все колонки в любом порядке)
head(dbGetQuery(mydb, "SELECT * FROM Users ORDER BY username;"))

# 2. 5 пользователей, которые зарегистрировались последними (все колонки в любом порядке)
dbGetQuery(mydb, "SELECT * FROM Users ORDER BY registered DESC LIMIT 5;")

# 3. Топ 5 пользователей по числу прослушиваний (все колонки в любом порядке)
dbGetQuery(mydb, "SELECT * FROM Listened
           JOIN Users ON id=user_id 
           GROUP BY username 
           ORDER BY COUNT (song_id) DESC
           LIMIT 5
           ;")

# 4. Информацию об исполнителях и количестве их альбомов (имя исполнителя|число)
head(dbGetQuery(mydb, "SELECT Artists.name, 
           COUNT(Albums.artist_id) AS 'number_of_albums_of_artist'
           FROM Albums 
           JOIN Artists ON Artists.id=Albums.artist_id
           GROUP BY Artists.id
           ;"))

# 5. Информацию об исполнителях и количестве их песен (имя исполнителя|число)
head(dbGetQuery(mydb, "SELECT Artists.name, 
           COUNT(Songs.id) AS 'number_of_songs_of_artist'
           FROM Songs 
           JOIN Albums ON Albums.id=Songs.Album_id  
           JOIN Artists ON Artists.id=Albums.artist_id
           GROUP BY Artists.id
           ;"))

# 6. Самый длинный альбом по числу песен. (имя исполнителя|название альбома|число)
dbGetQuery(mydb, "SELECT Artists.name, Albums.name, 
           COUNT(Songs.id) AS 'number_of_songs_in_album' 
           FROM Songs 
           JOIN Albums ON Albums.id=Songs.album_id
           JOIN Artists ON Artists.id=Albums.artist_id 
           GROUP BY Albums.id 
           ORDER BY number_of_songs_in_album DESC
           LIMIT 1
           ;")

# 7. Самый длинный альбом по суммарной продолжительности. (имя исполнителя|название альбома|число)
dbGetQuery(mydb, "SELECT Artists.name, Albums.name, 
           TOTAL(Songs.duration) AS 'duration_of_album' 
           FROM Songs 
           JOIN Albums ON Albums.id=Songs.album_id
           JOIN Artists ON Artists.id=Albums.artist_id 
           GROUP BY Albums.id 
           ORDER BY duration_of_album DESC
           LIMIT 1
           ;")

# 8. Альбом самой большой средней продолжительностью трека. (имя исполнителя|название альбома|число)
dbGetQuery(mydb, "SELECT Artists.name, Albums.name, 
           AVG(Songs.duration) AS 'mean_duration_of_song'
           FROM Songs 
           JOIN Albums ON Albums.id=Songs.album_id
           JOIN Artists ON Artists.id=Albums.artist_id 
           GROUP BY Albums.id 
           ORDER BY mean_duration_of_song DESC 
           LIMIT 1
           ;")

# 9. Топ 5 самых прослушиваемых треков. (имя исполнителя|название альбома|название песни|число)
dbGetQuery(mydb, "SELECT Artists.name, Albums.name, Songs.name,
           COUNT(Listened.song_id) AS 'most_listened_songs'
           FROM Listened
           JOIN Songs ON Songs.id=Listened.song_id
           JOIN Albums ON Albums.id=Songs.album_id
           JOIN Artists ON Artists.id=Albums.artist_id 
           GROUP BY Songs.id
           ORDER BY most_listened_songs DESC 
           LIMIT 5
           ;")

# 10. Найдите год, что песни, выпущенные в этом году, слушают больше всего (год|количество прослушиваний)
dbGetQuery(mydb, "SELECT Albums.release_year,
           COUNT(Listened.song_id) AS 'number_of_plays'
           FROM Listened 
           JOIN Songs ON Songs.id=Listened.song_id
           JOIN Albums ON Albums.id=Songs.album_id
           GROUP BY Albums.release_year
           ORDER BY number_of_plays DESC 
           LIMIT 1
           ;")

# 11. Для пользователя с id=47 найдите топ 20 последних прослушанных треков. (имя исполнителя|название альбома|название песни|когда)
dbGetQuery(mydb, "SELECT Artists.name, Albums.name, Songs.name, Listened.start_time 
           FROM Listened
           JOIN Songs ON Songs.id=Listened.song_id
           JOIN Albums ON Albums.id=Songs.album_id
           JOIN Artists ON Artists.id=Albums.artist_id
           WHERE user_id=47
           ORDER BY Listened.start_time DESC 
           LIMIT 20
           ;")

# 12. Для каждого пользователя и каждой песни, которую пользователь прослушал, найдите количество прослушиваний. (имя пользователя|имя исполнителя|название альбома|название песни|число). Подсказка – можно использовать пару колонок в group by.
head(dbGetQuery(mydb, "SELECT Users.username, Artists.name, Albums.name, Songs.name,
           COUNT(Listened.song_id)
           FROM Listened 
           JOIN Songs ON Songs.id=Listened.song_id
           JOIN Albums ON Albums.id=Songs.album_id
           JOIN Artists ON Artists.id=Albums.artist_id 
           JOIN Users ON Users.id=Listened.user_id
           GROUP BY Users.id, Songs.id
           ;"))


dbDisconnect(mydb)
```